title: Abikoye Michael
image: passport photo.jpeg
image2: WhatsApp Image 2025-06-06 at 4.47.42 PM (1).jpeg
description: Passionate about data analysis and visualization, I use tools like Power BI and Python to turn raw data into actionable insights. This repository showcases projects focused on improving decision-making in finance, rural development, and business performance.
theme: jekyll-theme-minimal
