title: Abikoye Michael
description: Passionate about data analysis and visualization, I use tools like Power BI and Python to turn raw data into actionable insights. This repository showcases projects focused on improving decision-making in finance, rural development, and business performance.
theme: jekyll-theme-minimal
